library(moments)
attach(Q9_a)
kurtosis(speed)
skewness(speed)
hist(speed)
kurtosis(dist)
skewness(dist)
hist(dist)
attach(Q9_b)
skewness(SP)
kurtosis(SP)
hist(SP)
skewness(WT)
kurtosis(WT)
hist(WT)
qqnorm(Cars$MPG)
qqline(Cars$MPG, col= "red")
attach(wc_at_)
qqnorm(wc_at_$Waist)
qqnorm(wc_at_$AT)
qnorm(0.95)
qnorm(0.97)
qnorm(0.80)
pt(-0.47, df = 17)